class Project
	attr :vars 
	def set_vars	
		@vars = {
		    mtpid: ['project-id', 'int'],
		    title: ['title', 'string'],
		    description: ['description', 'string'],
		    tot_proj_cost: ['total-cost', 'int'],
		    contact_first_name: ['contact-first-name', 'string'],
		    contact_last_name: ['contact-last-name', 'string'],
		    contact_phone: ['contact-phone', 'string'],
		    contact_email: ['contact-email', 'string'],
		    est_cost_year: ['constant-dollar-year', 'int'],
		    completion_year: ['completion-year', 'int'],
		    mtp_status: ['mtp-status', 'int'],
		    project_on: ['location', 'string'],
		    project_from: ['endpoint-a', 'string'],
		    project_to: ['endpoint-b', 'string'],
		    mile_post_from: ['milepost-a', 'decimal'],
		    mile_post_to: ['milepost-b', 'decimal'],
		    county_id: ['county-id', 'int'],
		    func_class_id: ['functional-class', 'int'],
		    start_year: ['start-year', 'int'],
		    primary_improvement_type_id: ['primary-improvement-type-id', 'string'],
		    p_a1a: ['prioritization-a1a','bit'],		    
		    p_a1b: ["prioritization-a1b",'bit'],		    
		    p_a2a: ["prioritization-a2a",'bit'],
		    p_a2b: ["prioritization-a2b",'bit'],		    
		    p_a3: ["prioritization-a3", 'bit'],	    
		    p_a4: ["prioritization-a4", 'bit'],   
		    p_c1a: ["prioritization-c1a",'bit'],		    
		    p_c1b: ["prioritization-c1b",'bit'],		    
		    p_c1c: ["prioritization-c1c",'bit'],
		    p_c2a: ["prioritization-c2a",'bit'],
		    p_c2b: ["prioritization-c2b",'bit'],
		    p_c3: ["prioritization-c3", 'bit'],
		    p_c4: ["prioritization-c4", 'bit'],
		    p_c5: ["prioritization-c5", 'bit'],
		    p_f1: ["prioritization-f1", 'bit'],
		    p_f2: ["prioritization-f2", 'bit'],
		    p_f3: ["prioritization-f3", 'bit'],
		    p_f4a: ["prioritization-f4a",'bit'],
		    p_f4b: ["prioritization-f4b",'bit'],
		    p_f5: ["prioritization-f5", 'bit'],
		    p_f6: ["prioritization-f6", 'bit'],
		    p_j1a: ["prioritization-j1a",'bit'],
		    p_j1b: ["prioritization-j1b",'bit'],
		    p_j2: ["prioritization-j2", 'bit'],
		    p_j3: ["prioritization-j3", 'bit'],
		    p_j4: ["prioritization-j4", 'bit'],
		    p_m1: ["prioritization-m1", 'bit'],
		    p_m2: ["prioritization-m2", 'bit'],
		    p_m3: ["prioritization-m3", 'bit'],
		    p_m4: ["prioritization-m4", 'bit'],
		    p_m5: ["prioritization-m5", 'bit'],
		    p_m6: ["prioritization-m6", 'bit'],
		    p_m7: ["prioritization-m7", 'bit'],
		    p_o1: ["prioritization-o1", 'bit'],
		    p_o2a: ["prioritization-o2a",'bit'],
		    p_o2b: ["prioritization-o2b",'bit'],
		    p_o2c: ["prioritization-o2c",'bit'],
		    p_o3a: ["prioritization-o3a",'bit'],
		    p_o3b: ["prioritization-o3b",'bit'],
		    p_o3c: ["prioritization-o3c",'bit'],
		    p_s1a: ["prioritization-s1a",'bit'],
		    p_s1b: ["prioritization-s1b",'bit'],
		    p_s1c: ["prioritization-s1c",'bit'],
		    p_s2: ["prioritization-s2", 'bit'],
		    p_t1: ["prioritization-t1", 'bit'],
		    p_t2: ["prioritization-t2", 'bit'],
		    p_t3: ["prioritization-t3", 'bit'],
		    p_t4: ["prioritization-t4", 'bit'],
		    p_w1a: ["prioritization-w1a",'bit'],
		    p_w1b: ["prioritization-w1b",'bit'],
		    p_w1c: ["prioritization-w1c",'bit'],
		    p_w1d: ["prioritization-w1d",'bit'],
		    p_w2: ["prioritization-w2", 'bit'],
		    p_w4a: ["prioritization-w4a",'bit'],
		    p_w4b: ["prioritization-w4b",'bit'],
		   }
		 end
end